# Generated by Django 6.1 on 2026-08-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('designation', models.CharField(choices=[('HR_EXECUTIVE', 'HR Executive'), ('HR_MANAGER', 'HR Manager'), ('TALENT_ACQUISITION', 'Talent Acquisition Specialist'), ('SENIOR_RECRUITER', 'Senior Recruiter'), ('TECHNICAL_RECRUITER', 'Technical Recruiter')], max_length=100, verbose_name='Designation')),
                ('department', models.CharField(choices=[('HUMAN_RESOURCES', 'Human Resources'), ('RECRUITMENT', 'Recruitment'), ('TECHNICAL', 'Technical'), ('OPERATIONS', 'Operations')], max_length=100, verbose_name='Department')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='recruiters/profile_images/', verbose_name='Profile Image')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('is_primary_recruiter', models.BooleanField(default=False, verbose_name='Primary Recruiter')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='companies.company', verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
                'db_table': 'recruiters',
                'ordering': ['user__first_name'],
            },
        ),
    ]
