# Generated by Django 6.1 on 2026-08-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes/', verbose_name='Resume')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='candidates/profile_images/', verbose_name='Profile Image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not to Say')], max_length=25, null=True, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone Number')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Profile')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio Website')),
                ('highest_qualification', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School'), ('DIPLOMA', 'Diploma'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('PHD', 'Ph.D.'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Highest Qualification')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialization')),
                ('college_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='College Name')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='CGPA')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('current_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Company')),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current CTC')),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expected CTC')),
                ('current_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Location')),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Location')),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Notice Period (Days)')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Professional Summary')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='Profile Completed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
                'ordering': ['user__first_name'],
            },
        ),
    ]
