# Generated by Django 6.1 on 2026-08-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='career_status',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('EXPERIENCED', 'Experienced')], default='FRESHER', max_length=20, verbose_name='Career Status'),
        ),
    ]
