# Generated by Django 6.1 on 2026-08-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_career_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('education_level', models.CharField(choices=[('SECONDARY', 'Secondary School'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=30)),
                ('institution_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_type', models.CharField(choices=[('CGPA', 'CGPA'), ('PERCENTAGE', 'Percentage'), ('GRADE', 'Grade')], max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_educations',
                'ordering': ['-end_year', '-start_year'],
            },
        ),
    ]
