# Generated by Django 6.1 on 2026-08-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('title', models.CharField(max_length=255, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('ACCOUNT', 'Account'), ('JOB', 'Job'), ('APPLICATION', 'Application'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('OTP', 'OTP'), ('PASSWORD', 'Password'), ('EMAIL', 'Email')], default='SYSTEM', max_length=30, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('sent_email', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
