# Generated by Django 6.1 on 2026-08-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('rejection_stage', models.CharField(choices=[('APPLICATION_REVIEW', 'Application Review'), ('HR_SCREENING', 'HR Screening'), ('TECHNICAL_INTERVIEW', 'Technical Interview'), ('MANAGERIAL_INTERVIEW', 'Managerial Interview'), ('FINAL_INTERVIEW', 'Final Interview'), ('OFFER_STAGE', 'Offer Stage')], max_length=30, verbose_name='Rejection Stage')),
                ('rejection_reason', models.CharField(choices=[('SKILLS_MISMATCH', 'Skills Mismatch'), ('EXPERIENCE_MISMATCH', 'Experience Mismatch'), ('EDUCATION_MISMATCH', 'Education Mismatch'), ('COMMUNICATION_SKILLS', 'Communication Skills'), ('TECHNICAL_KNOWLEDGE', 'Technical Knowledge'), ('CULTURAL_FIT', 'Cultural Fit'), ('SALARY_EXPECTATION', 'Salary Expectation'), ('POSITION_FILLED', 'Position Filled'), ('CANDIDATE_WITHDREW', 'Candidate Withdrew'), ('OTHER', 'Other')], max_length=255, verbose_name='Rejection Reason')),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback visible to the candidate.', null=True, verbose_name='Feedback')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('rejected_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejected At')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='applications.application', verbose_name='Application')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By')),
            ],
            options={
                'verbose_name': 'Rejection',
                'verbose_name_plural': 'Rejections',
                'db_table': 'rejections',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
