# Generated by Django 6.1 on 2026-08-07 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SEND', 'Send'), ('DOWNLOAD', 'Download')], max_length=30, verbose_name='Action')),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('COMPANIES', 'Companies'), ('RECRUITERS', 'Recruiters'), ('CANDIDATES', 'Candidates'), ('JOBS', 'Jobs'), ('APPLICATIONS', 'Applications'), ('INTERVIEWS', 'Interviews'), ('OFFERS', 'Offers'), ('NOTIFICATIONS', 'Notifications'), ('AUTHENTICATION', 'Authentication'), ('SYSTEM', 'System')], max_length=50, verbose_name='Module')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='Object ID')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
