# Generated by Django 6.1 on 2026-08-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('interview_round', models.CharField(choices=[('HR', 'HR Round'), ('TECHNICAL_1', 'Technical Round 1'), ('TECHNICAL_2', 'Technical Round 2'), ('MANAGERIAL', 'Managerial Round'), ('FINAL_HR', 'Final HR Round')], max_length=30, verbose_name='Interview Round')),
                ('interviewer_name', models.CharField(max_length=255, verbose_name='Interviewer Name')),
                ('interviewer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Interviewer Email')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(verbose_name='Scheduled Time')),
                ('interview_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=20, verbose_name='Interview Mode')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Meeting Link')),
                ('venue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Interview Venue')),
                ('interview_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=30, verbose_name='Interview Status')),
                ('interviewer_feedback', models.TextField(blank=True, null=True, verbose_name='Interviewer Feedback')),
                ('interviewer_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Interviewer Rating')),
                ('recommendation', models.CharField(blank=True, choices=[('STRONG_HIRE', 'Strong Hire'), ('HIRE', 'Hire'), ('HOLD', 'Hold'), ('REJECT', 'Reject')], max_length=30, null=True, verbose_name='Recommendation')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'interviews',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
