# Generated by Django 6.1 on 2026-08-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('application_number', models.CharField(max_length=30, unique=True, verbose_name='Application Number')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('application_status', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('OFFER_RELEASED', 'Offer Released'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('OFFER_DECLINED', 'Offer Declined')], default='APPLIED', max_length=30, verbose_name='Application Status')),
                ('source', models.CharField(choices=[('COMPANY_PORTAL', 'Company Portal'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('NAUKRI', 'Naukri'), ('REFERRAL', 'Employee Referral'), ('CAMPUS', 'Campus Placement'), ('WALK_IN', 'Walk-in'), ('OTHER', 'Other')], default='COMPANY_PORTAL', max_length=30, verbose_name='Application Source')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Cover Letter')),
                ('resume_snapshot', models.FileField(blank=True, null=True, upload_to='applications/resumes/', verbose_name='Resume Snapshot')),
                ('recruiter_notes', models.TextField(blank=True, null=True, verbose_name='Recruiter Notes')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Recruiter Rating')),
                ('is_shortlisted', models.BooleanField(default=False, verbose_name='Shortlisted')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile', verbose_name='Candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application')],
            },
        ),
    ]
