# Generated by Django 6.1 on 2026-08-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('offer_number', models.CharField(max_length=30, unique=True, verbose_name='Offer Number')),
                ('offered_job_title', models.CharField(max_length=255, verbose_name='Offered Job Title')),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Offered Salary')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('offer_expiry_date', models.DateField(verbose_name='Offer Expiry Date')),
                ('offer_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20, verbose_name='Offer Status')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/', verbose_name='Offer Letter')),
                ('hr_notes', models.TextField(blank=True, null=True, verbose_name='HR Notes')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='Declined At')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applications.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
