# Generated by Django 6.1 on 2026-08-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_code', models.CharField(max_length=30, unique=True, verbose_name='Job Code')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=30, verbose_name='Employment Type')),
                ('workplace_type', models.CharField(choices=[('ON_SITE', 'On-site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], max_length=30, verbose_name='Workplace Type')),
                ('experience_level', models.CharField(choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior'), ('MID_LEVEL', 'Mid-Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], max_length=30, verbose_name='Experience Level')),
                ('minimum_experience', models.PositiveIntegerField(default=0, verbose_name='Minimum Experience')),
                ('maximum_experience', models.PositiveIntegerField(default=0, verbose_name='Maximum Experience')),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Salary')),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Salary')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('vacancies', models.PositiveIntegerField(default=1, verbose_name='Vacancies')),
                ('location', models.CharField(max_length=150, verbose_name='Job Location')),
                ('required_skills', models.TextField(verbose_name='Required Skills')),
                ('qualification', models.CharField(max_length=100, verbose_name='Minimum Qualification')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsibilities')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Job Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Job')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='Company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiters.recruiterprofile', verbose_name='Recruiter')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
