# Generated by Django 6.1 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('company_code', models.CharField(max_length=20, unique=True, verbose_name='Company Code')),
                ('company_email', models.EmailField(max_length=254, unique=True, verbose_name='Company Email')),
                ('company_phone', models.CharField(max_length=15, unique=True, verbose_name='Company Phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('industry', models.CharField(choices=[('INFORMATION_TECHNOLOGY', 'Information Technology'), ('HEALTHCARE', 'Healthcare'), ('FINANCE', 'Finance'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('TELECOMMUNICATION', 'Telecommunication'), ('LOGISTICS', 'Logistics'), ('CONSTRUCTION', 'Construction'), ('OTHER', 'Other')], max_length=50, verbose_name='Industry')),
                ('company_size', models.CharField(choices=[('STARTUP', 'Startup (1–50 Employees)'), ('SMALL', 'Small (51–200 Employees)'), ('MEDIUM', 'Medium (201–1000 Employees)'), ('ENTERPRISE', 'Enterprise (1000+ Employees)')], max_length=50, verbose_name='Company Size')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['company_name'],
            },
        ),
    ]
