# Generated by Django 6.1 on 2026-09-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('STARTUP', 'Startup (1–50 Employees)'), ('SMALL', 'Small (51–200 Employees)'), ('MEDIUM', 'Medium (201–1000 Employees)'), ('ENTERPRISE', 'Enterprise (1000+ Employees)')], max_length=50, null=True, verbose_name='Company Size'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('INFORMATION_TECHNOLOGY', 'Information Technology'), ('HEALTHCARE', 'Healthcare'), ('FINANCE', 'Finance'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('TELECOMMUNICATION', 'Telecommunication'), ('LOGISTICS', 'Logistics'), ('CONSTRUCTION', 'Construction'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
    ]
